const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('autoSpaDesktop', {
    runtime: 'electron',
    mode: 'offline-shell',
    dashboard: () => ipcRenderer.invoke('desktop:dashboard'),
    listCustomers: (search) => ipcRenderer.invoke('desktop:customers:list', search),
    createCustomer: (input) => ipcRenderer.invoke('desktop:customers:create', input),
    listVehicles: (customerUuid) => ipcRenderer.invoke('desktop:vehicles:list', customerUuid),
    createVehicle: (input) => ipcRenderer.invoke('desktop:vehicles:create', input),
    listJobs: () => ipcRenderer.invoke('desktop:jobs:list'),
    createJob: (input) => ipcRenderer.invoke('desktop:jobs:create', input),
    updateJobStatus: (input) => ipcRenderer.invoke('desktop:jobs:update-status', input),
    listServices: () => ipcRenderer.invoke('desktop:catalog:services'),
    listProducts: () => ipcRenderer.invoke('desktop:catalog:products'),
    listPaymentMethods: () => ipcRenderer.invoke('desktop:catalog:payment-methods'),
    listSales: () => ipcRenderer.invoke('desktop:sales:list'),
    checkout: (input) => ipcRenderer.invoke('desktop:pos:checkout', input),
    financeOverview: (range) => ipcRenderer.invoke('desktop:finance:overview', range),
    listExpenses: (range) => ipcRenderer.invoke('desktop:finance:expenses:list', range),
    createExpense: (input) => ipcRenderer.invoke('desktop:finance:expenses:create', input),
    syncStatus: () => ipcRenderer.invoke('desktop:sync:status'),
    syncNow: () => ipcRenderer.invoke('desktop:sync:now'),
    pullBootstrap: () => ipcRenderer.invoke('desktop:sync:bootstrap'),
    checkSession: () => ipcRenderer.invoke('desktop:sync:check'),
    openCloudLogin: () => ipcRenderer.invoke('desktop:cloud:login'),
    goOnline: () => ipcRenderer.invoke('desktop:ui:go-online'),
    goOffline: () => ipcRenderer.invoke('desktop:ui:go-offline'),
});
